route:
  receiver: 'slack'

receivers:
  - name: 'slack'
    slack_configs:
      - send_resolved: true
        text: "{{ .CommonAnnotations.description }}"
#        username: '<username>'
#        channel: '#<channel-name>'
#        api_url: '<incoming-webhook-url>'